file_path: "data/ffcv/imagenet"
channel: 3
num_classes: 1000
build:
  root_path: "data/imagenet"
  data_name: "imagenet"
  num_workers: 4
  batch_size: 512
  max_resolution: 256
  seed: 42
transform:
  image_size: 224
  re_size: 256
mixup_params:
  mixup_alpha: 0.8
  cutmix_alpha: 1.0
  cutmix_minmax: null
  prob: 1.0
  switch_prob: 0.5
  mode: "batch"
  label_smoothing: 0.1
